### PR TITLE
:white_check_mark:Implement test for GET dashboard

### PR DESCRIPTION
**Pull request by VladOSIO2**

### CODE REVIEW

**Comment by VladOSIO2** [comment]
It seems that there is the same test appeared at main out of nowhere. This is what happens when the development process shatters from the pressure of the deadline drawing near.

**Comment by CalculusEnjoyer** [comment]
> There is no coverage information present for the Files changed

|Total Project Coverage|83.16%|:green_apple:|
|:-|:-:|:-:|

**Comment by VladOSIO2** [comment]
Merged two similar tests into one, The Test to end all Tests

**Review by CalculusEnjoyer — APPROVED** [review]
Very nice test)

**Pull request merged**
