### PR TITLE
👔 Add InterviewerSlot checking for overlapping.

### PR DESCRIPTION
**Pull request by CalculusEnjoyer**
Add a method in IntetviewerValidator for checking if the new slot is overlapping with already existing slots and write tests for it.

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [52%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerValidator.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e08737179aaf753a9a11a9359e013dcac77ef91b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fvalidation%2FInterviewerValidator.java)|52%|:green_apple:|

|Total Project Coverage|44.34%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [52.76%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerValidator.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/78814fbd481e3597b8479b641117bf0b34bfad84/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fvalidation%2FInterviewerValidator.java)|52.76%|:green_apple:|

|Total Project Coverage|44.38%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [51.61%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerValidator.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/49aaee200a97451ead11dbd8ccf8fe6f99dd56b4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fvalidation%2FInterviewerValidator.java)|51.61%|:green_apple:|

|Total Project Coverage|44.32%|:green_apple:|
|:-|:-:|:-:|

**Review by VladOSIO2 — APPROVED** [review]
Good

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [41.29%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerValidator.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/6ce56d1db0872c0b1ae86e0e608e1adcb42cda62/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fvalidation%2FInterviewerValidator.java)|41.29%|:green_apple:|

|Total Project Coverage|43.22%|:green_apple:|
|:-|:-:|:-:|

**Pull request merged**
