### PR TITLE
:bricks: Implement template endpoints in CommonController & InterviewerController

### PR DESCRIPTION
**Pull request by VladOSIO2**

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [9.73%]|:x:|
|:-|:-:|:-:|
|[CommonController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/3a3284fdd0f167d768d464c86c823ca3a90fe369/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCommonController.java)|25%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/3a3284fdd0f167d768d464c86c823ca3a90fe369/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|15.38%|:green_apple:|
|[InterviewerController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/3a3284fdd0f167d768d464c86c823ca3a90fe369/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|6.72%|:x:|

|Total Project Coverage|26.4%|:green_apple:|
|:-|:-:|:-:|

**Comment by olexandra-shokotko** [comment]
Why updateInterviewerSlot() in CoordinatorController was removed?

**Review by CalculusEnjoyer — APPROVED** [review]
For real, updateInterviewerSlot() should be in CoordinatorController

**Comment by VladOSIO2** [comment]
updateInterviewerSlot() was not removed completely, it was just moved to InterviewerController (although it has a wrong name  in that class (but right JavaDoc description) so this is a mistake that I must fix of course, and maybe a reason that lead to misunderstanding) due to relation of the slots to the interviewer, and /interviewers mapping in POST request. I'm asking to discuss this problem on our next daily meeting to make things clear.

**Review by Archasmiel — APPROVED** [review]
OK

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [9.73%]|:x:|
|:-|:-:|:-:|
|[CommonController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/fdee7ac5f3c8473ea569b430d6fa772ed7325581/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCommonController.java)|25%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/fdee7ac5f3c8473ea569b430d6fa772ed7325581/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|15.38%|:green_apple:|
|[InterviewerController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/fdee7ac5f3c8473ea569b430d6fa772ed7325581/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|6.72%|:x:|

|Total Project Coverage|25.22%|:green_apple:|
|:-|:-:|:-:|

**Pull request merged**
