### PR TITLE
✅ Add tests for updating and creating booking endpoints

### PR DESCRIPTION
**Pull request by CalculusEnjoyer**
Add tests for updating and creating booking endpoints

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
> There is no coverage information present for the Files changed

|Total Project Coverage|57.2%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [87.19%]|:green_apple:|
|:-|:-:|:-:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bb8eddae53587a8c1466df4c918b20102cda5ffd/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|91.01%|:green_apple:|
|[CommonController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bb8eddae53587a8c1466df4c918b20102cda5ffd/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCommonController.java)|27.27%|:green_apple:|

|Total Project Coverage|57.2%|:green_apple:|
|:-|:-:|:-:|

**Review by VladOSIO2 — APPROVED** [review]
That's a good load of tests, approved!

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [86.65%]|:green_apple:|
|:-|:-:|:-:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/42a33a3f9fb640ccd73ad45144f4f5e40f61d34c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|90.96%|:green_apple:|
|[CommonController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/42a33a3f9fb640ccd73ad45144f4f5e40f61d34c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCommonController.java)|25%|:green_apple:|

|Total Project Coverage|65.46%|:green_apple:|
|:-|:-:|:-:|

**Pull request merged**
