### PR TITLE
Add one-to-many relation in slots and refactor names of foreign keys columns

### PR DESCRIPTION
**Pull request by CalculusEnjoyer**
image
According to requirements, bookings have to be linked to slots.

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [32.56%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0ac90500730e4bdb9fa9b32cd753e2419865a2c9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|50.96%|:green_apple:|
|[InterviewerSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0ac90500730e4bdb9fa9b32cd753e2419865a2c9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerSlot.java)|45.38%|:green_apple:|
|[Candidate.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0ac90500730e4bdb9fa9b32cd753e2419865a2c9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidate.java)|20.63%|:green_apple:|
|[Interviewer.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0ac90500730e4bdb9fa9b32cd753e2419865a2c9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewer.java)|17.81%|:green_apple:|
|[Booking.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0ac90500730e4bdb9fa9b32cd753e2419865a2c9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|4.76%|:x:|

|Total Project Coverage|25.78%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [15.19%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|50.96%|:green_apple:|
|[InterviewerSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerSlot.java)|45.38%|:green_apple:|
|[Candidate.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidate.java)|18.6%|:green_apple:|
|[Interviewer.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewer.java)|15.09%|:green_apple:|
|[InterviewerController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|7.56%|:x:|
|[CandidateController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|5.45%|:x:|
|[Booking.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|4.76%|:x:|
|[CandidateSlotDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotDto.java)|0%|:x:|
|[BookingDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|0%|:x:|
|[CandidateDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateDto.java)|0%|:x:|
|[UserDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FUserDto.java)|0%|:x:|
|[InterviewerDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerDto.java)|0%|:x:|
|[InterviewerSlotDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7d04b48c039d77c323fad757f40c5f727041f0a3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|0%|:x:|

|Total Project Coverage|24.71%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [16.74%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|50.96%|:green_apple:|
|[InterviewerSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerSlot.java)|45.38%|:green_apple:|
|[Candidate.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidate.java)|18.6%|:green_apple:|
|[Interviewer.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewer.java)|15.09%|:green_apple:|
|[InterviewerController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|7.56%|:x:|
|[CandidateController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|5.45%|:x:|
|[Booking.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|4.76%|:x:|
|[CandidateSlotDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotDto.java)|0%|:x:|
|[BookingDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|0%|:x:|
|[CandidateDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateDto.java)|0%|:x:|
|[UserDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FUserDto.java)|0%|:x:|
|[InterviewerDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerDto.java)|0%|:x:|
|[InterviewerSlotDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/bd1d4adc34f8979e0fe0f29df9f5fd4fdf100fd7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|0%|:x:|

|Total Project Coverage|26.7%|:green_apple:|
|:-|:-:|:-:|

**Review by Archasmiel — APPROVED** [review]
All is OK

**Pull request merged**
