### PR TITLE
Implement Interviewer GET endpoints (#75, #77, #70)

### PR DESCRIPTION
**Pull request by VladOSIO2**
- Implement endpoint `GET /{interviewerId}/slots/current_week` for getting the current week interviewer slots (#75)
- Implement endpoint `GET /{interviewerId}/slots/next_week` for getting the next week interviewer slots (#77)
- Remove POST "/addSlots", GET "/getSlots", GET "/delSlots", test endpoints created on the start of the development (#70)

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [50.72%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0c1b1770adc13088dfd6528d432a654e62575dff/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|92.06%|:green_apple:|
|[InterviewerController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0c1b1770adc13088dfd6528d432a654e62575dff/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|16%|:green_apple:|

|Total Project Coverage|40.26%|:green_apple:|
|:-|:-:|:-:|

**Comment by VladOSIO2** [comment]
Will resolve the merge conflict after the PR #98 will be closed

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [46.1%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/740f25162631a9b1869626fc711a806a59a8ee0d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|80.3%|:green_apple:|
|[InterviewerController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/740f25162631a9b1869626fc711a806a59a8ee0d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|16%|:green_apple:|

|Total Project Coverage|42.07%|:green_apple:|
|:-|:-:|:-:|

**Review by olexandra-shokotko — APPROVED** [review]
All is good

**Pull request merged**
