### PR TITLE
Implement services, DTOs, DB basic integration and tests

### PR DESCRIPTION
**Pull request by Archasmiel**

### CODE REVIEW

**Comment by Archasmiel** [comment]
PostgreSQL need to be launched correctly.

**Review by grata-salve — COMMENTED** [review]
All OK, but using of ModelMapper or MapStruct (even better) will be more convenient than "of" methods in DTO's and models. Logic remain the same, but it will allow avoid hardcode.

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [16.24%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|63.64%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|58.33%|:green_apple:|
|[InterviewerSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerSlot.java)|56.6%|:green_apple:|
|[CandidateService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|51.61%|:green_apple:|
|[InterviewerService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|44.44%|:green_apple:|
|[CandidateSlotDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotDto.java)|34.38%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|22.06%|:green_apple:|
|[User.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FUser.java)|9.09%|:x:|
|[InterviewerController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|7.69%|:x:|
|[Candidate.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidate.java)|6.98%|:x:|
|[CandidateController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|5.88%|:x:|
|[Interviewer.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewer.java)|5.66%|:x:|
|[Booking.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|3.61%|:x:|
|[CandidateDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateDto.java)|0%|:x:|
|[UserDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FUserDto.java)|0%|:x:|
|[BookingDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|0%|:x:|
|[InterviewerDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/e37828f1ad244deab06bad335e44ce1c7a04d784/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerDto.java)|0%|:x:|

|Total Project Coverage|23.71%|:green_apple:|
|:-|:-:|:-:|

**Review by VladOSIO2 — APPROVED** [review]
OK

**Pull request merged**
