### PR TITLE
Connect OAuth2 to database.

### PR DESCRIPTION
**Pull request by grata-salve**
:arrow_up: Upgrade dependency.
:wrench: Update application properties.
:sparkles: User data is added to our database upon registration.
:white_check_mark: add email field in User model.

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [24.76%]|:green_apple:|
|:-|:-:|:-:|
|[SecurityConfig.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/a1504144bbadddb9841b5a1b5848243f677712e5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[UserService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/a1504144bbadddb9841b5a1b5848243f677712e5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|50%|:green_apple:|
|[SecurityController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/a1504144bbadddb9841b5a1b5848243f677712e5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fauth%2FSecurityController.java)|21.43%|:green_apple:|
|[User.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/a1504144bbadddb9841b5a1b5848243f677712e5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FUser.java)|6.98%|:x:|

|Total Project Coverage|25.6%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [15.23%]|:green_apple:|
|:-|:-:|:-:|
|[SecurityConfig.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7604c5b8973b7250589b2bba9347e0d63a3e0014/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[UserService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7604c5b8973b7250589b2bba9347e0d63a3e0014/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|35.29%|:green_apple:|
|[SecurityController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7604c5b8973b7250589b2bba9347e0d63a3e0014/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fauth%2FSecurityController.java)|10.47%|:green_apple:|
|[User.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/7604c5b8973b7250589b2bba9347e0d63a3e0014/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FUser.java)|6.98%|:x:|

|Total Project Coverage|23.12%|:green_apple:|
|:-|:-:|:-:|

**Comment by olexandra-shokotko** [comment]
All is good. But there was changed a spring.datasource.password. Why it needed to be changed? We need to change our password for postgres user or maybe it is better to keep this information in another file?

**Review by Archasmiel — APPROVED** [review]
OK

**Pull request merged**
