### PR TITLE
:sparkles: Candidate Postman collection update

### PR DESCRIPTION
**Pull request by Archasmiel**

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [100%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateValidator.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/46a9e3f4f4a691653e2ef431e64a24071c3eeec3/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fvalidation%2FCandidateValidator.java)|100%|:green_apple:|

|Total Project Coverage|75.74%|:green_apple:|
|:-|:-:|:-:|

**Comment by Archasmiel** [comment]
image

**Comment by Archasmiel** [comment]
Will merge after all PRs are ready.

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [100%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateValidator.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/b0a5f596f4f2d20378d03ce0db29694e734145c6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fvalidation%2FCandidateValidator.java)|100%|:green_apple:|

|Total Project Coverage|75.56%|:green_apple:|
|:-|:-:|:-:|

**Pull request merged**
