### PR TITLE
Add @Table annotations

### PR DESCRIPTION
**Pull request by CalculusEnjoyer**
Add @Table annotations in order to add tables to the database properly.

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [6.04%]|:x:|
|:-|:-:|:-:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/5d32d336fa9dc1e32c0178a126b44d6d1381fdcc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|9.09%|:x:|
|[User.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/5d32d336fa9dc1e32c0178a126b44d6d1381fdcc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FUser.java)|9.09%|:x:|
|[Candidate.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/5d32d336fa9dc1e32c0178a126b44d6d1381fdcc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidate.java)|6.98%|:x:|
|[Interviewer.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/5d32d336fa9dc1e32c0178a126b44d6d1381fdcc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewer.java)|5.66%|:x:|
|[InterviewerSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/5d32d336fa9dc1e32c0178a126b44d6d1381fdcc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerSlot.java)|5.66%|:x:|
|[Booking.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/5d32d336fa9dc1e32c0178a126b44d6d1381fdcc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|3.61%|:x:|

|Total Project Coverage|21.87%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [22.64%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/5b2e277dc4a13baf14bcb7d4c63dc8d3dcc78508/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|63.64%|:green_apple:|
|[InterviewerSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/5b2e277dc4a13baf14bcb7d4c63dc8d3dcc78508/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerSlot.java)|56.6%|:green_apple:|
|[Candidate.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/5b2e277dc4a13baf14bcb7d4c63dc8d3dcc78508/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidate.java)|6.98%|:x:|
|[Interviewer.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/5b2e277dc4a13baf14bcb7d4c63dc8d3dcc78508/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewer.java)|5.66%|:x:|
|[Booking.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/5b2e277dc4a13baf14bcb7d4c63dc8d3dcc78508/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|3.61%|:x:|

|Total Project Coverage|23.71%|:green_apple:|
|:-|:-:|:-:|

**Review by Archasmiel — APPROVED** [review]
Nice

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [22.64%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/a9c44cadfcc44be169c43a7f4e38100324729c37/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|63.64%|:green_apple:|
|[InterviewerSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/a9c44cadfcc44be169c43a7f4e38100324729c37/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerSlot.java)|56.6%|:green_apple:|
|[Candidate.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/a9c44cadfcc44be169c43a7f4e38100324729c37/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidate.java)|6.98%|:x:|
|[Interviewer.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/a9c44cadfcc44be169c43a7f4e38100324729c37/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewer.java)|5.66%|:x:|
|[Booking.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/a9c44cadfcc44be169c43a7f4e38100324729c37/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|3.61%|:x:|

|Total Project Coverage|23.71%|:green_apple:|
|:-|:-:|:-:|

**Pull request merged**
