### PR TITLE
:recycle: Refactor InterviewerController endpoints to work with userId (#170)

### PR DESCRIPTION
**Pull request by VladOSIO2**

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [92.93%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/63ee81fba9bee956d5736d413d6f90f411d372ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|100%|:green_apple:|
|[InterviewerValidator.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/63ee81fba9bee956d5736d413d6f90f411d372ba/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fvalidation%2FInterviewerValidator.java)|86.42%|:green_apple:|

|Total Project Coverage|66.15%|:green_apple:|
|:-|:-:|:-:|

**Review by Archasmiel — COMMENTED** [review]
Great, but why so much Long objects? Can they be transferred to primitive?

**Review by Archasmiel — APPROVED** [review]
All is OK.
And one question up here.

**Comment by VladOSIO2** [comment]
> Great, but why so much Long objects? Can they be transferred to primitive?

If you mean the path variables - I will research that question, mainly about how the spring performs its object mapping, If you mean the validator methods - I`m passing the Long object ids from entities there, so I considered the unboxing was unnecessary.

To be honest, I haven't thought about the advantages of either using the primitive, or the wrapped object in a such use case. You gave a nice question to investigate how the Java and Spring works

**Pull request merged**
