### PR TITLE
:white_check_mark: Implemets tests, exception for unauthorized users, bug fixes and code optimization.

### PR DESCRIPTION
**Pull request by grata-salve**
Fix missed tests.

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
> There is no coverage information present for the Files changed

|Total Project Coverage|70.22%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
> There is no coverage information present for the Files changed

|Total Project Coverage|70.22%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
> There is no coverage information present for the Files changed

|Total Project Coverage|71.94%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
> There is no coverage information present for the Files changed

|Total Project Coverage|75.69%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
> There is no coverage information present for the Files changed

|Total Project Coverage|75.69%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [56.24%]|:green_apple:|
|:-|:-:|:-:|
|[FacebookService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/88b89fa1612eb9ccb182454eee73ce2e0c17c8bc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FFacebookService.java)|100%|:green_apple:|
|[SecurityCredentialsConfig.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/88b89fa1612eb9ccb182454eee73ce2e0c17c8bc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityCredentialsConfig.java)|100%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/88b89fa1612eb9ccb182454eee73ce2e0c17c8bc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|80.56%|:green_apple:|
|[UserService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/88b89fa1612eb9ccb182454eee73ce2e0c17c8bc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|24.59%|:green_apple:|
|[CommonController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/88b89fa1612eb9ccb182454eee73ce2e0c17c8bc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCommonController.java)|23.68%|:green_apple:|
|[JwtAuthenticationEntryPoint.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/88b89fa1612eb9ccb182454eee73ce2e0c17c8bc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fexceptions%2FJwtAuthenticationEntryPoint.java)|16.67%|:green_apple:|

|Total Project Coverage|75.38%|:green_apple:|
|:-|:-:|:-:|

**Comment by grata-salve** [comment]
:sparkles: Add exception for unauthorized users.
:bug: Returned erroneously deleted method and fixed /me endpoint
Add automatically Coordinator.
Minor fixes and code optimizations.

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [55.67%]|:green_apple:|
|:-|:-:|:-:|
|[FacebookService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/be0dc90bdf8b25ac60c5edb0abfc0bd4d571c805/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FFacebookService.java)|100%|:green_apple:|
|[SecurityCredentialsConfig.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/be0dc90bdf8b25ac60c5edb0abfc0bd4d571c805/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityCredentialsConfig.java)|100%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/be0dc90bdf8b25ac60c5edb0abfc0bd4d571c805/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|80.56%|:green_apple:|
|[UserService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/be0dc90bdf8b25ac60c5edb0abfc0bd4d571c805/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|24.59%|:green_apple:|
|[CommonController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/be0dc90bdf8b25ac60c5edb0abfc0bd4d571c805/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCommonController.java)|23.68%|:green_apple:|
|[CustomAccessDeniedHandler.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/be0dc90bdf8b25ac60c5edb0abfc0bd4d571c805/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fexceptions%2FCustomAccessDeniedHandler.java)|16.67%|:green_apple:|
|[JwtAuthenticationEntryPoint.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/be0dc90bdf8b25ac60c5edb0abfc0bd4d571c805/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fexceptions%2FJwtAuthenticationEntryPoint.java)|16.67%|:green_apple:|

|Total Project Coverage|75.19%|:green_apple:|
|:-|:-:|:-:|

**Review by Archasmiel — APPROVED** [review]
OK

**Pull request merged**
