### PR TITLE
create WeekService: methods for getting current and next week number

### PR DESCRIPTION
**Pull request by olexandra-shokotko**

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [17.31%]|:green_apple:|
|:-|:-:|:-:|
|[CommonController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/f1a07bcecb4c90d3b7acdb194c4fdc5d99dd27bb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCommonController.java)|35.29%|:green_apple:|
|[WeekService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/f1a07bcecb4c90d3b7acdb194c4fdc5d99dd27bb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2FWeekService.java)|8.57%|:x:|

|Total Project Coverage|24.9%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [10.23%]|:green_apple:|
|:-|:-:|:-:|
|[CommonController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/d972a763e02ea4cadc87e0c3baa3b75a2e9fc902/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCommonController.java)|35.29%|:green_apple:|
|[WeekService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/d972a763e02ea4cadc87e0c3baa3b75a2e9fc902/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2FWeekService.java)|4.23%|:x:|

|Total Project Coverage|24.22%|:green_apple:|
|:-|:-:|:-:|

**Comment by VladOSIO2** [comment]
WeekService and CommonController classes changes are fine. But, please, annotate non-related to PR theme changes if you wish to make them, like with pom.xml changes. As I reviewed, there is no dependency or configuration changes, but only the codestyle ones, but commits doesn't describe it, and there is no comment about it in this conversation.

Also refactoring the WeekService in '[refactor WeekService](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/pull/59/commits/d972a763e02ea4cadc87e0c3baa3b75a2e9fc902)' by removing the tests is not a good practice. I'm requesting to discuss that decision on the next daily meeting

**Review by VladOSIO2 — APPROVED** [review]
Approved after discussion on daily meeting. Tests will be implemented on the next PR

**Pull request merged**
