### PR TITLE
:recycle: Add BookingForm.java to return bookings in responses with id

### PR DESCRIPTION
**Pull request by CalculusEnjoyer**
Add BookingForm.java to return bookings in responses with id.
Minor changes:
Change data.sql that it does not depend on current date.
Fix the bug in *create booking* coordinator endpoint.
Optimise Dockerfile

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [54.57%]|:green_apple:|
|:-|:-:|:-:|
|[BookingForm.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/6d73071d086a93ac893d00794b01fa4bb9ee8790/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingForm.java)|56.73%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/6d73071d086a93ac893d00794b01fa4bb9ee8790/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|53.91%|:green_apple:|

|Total Project Coverage|58.43%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [60.99%]|:green_apple:|
|:-|:-:|:-:|
|[WeekService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/ae9d3eda29c170b8e1e84ea8ca39ddd76f58c84d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FWeekService.java)|100%|:green_apple:|
|[BookingForm.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/ae9d3eda29c170b8e1e84ea8ca39ddd76f58c84d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingForm.java)|56.73%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/ae9d3eda29c170b8e1e84ea8ca39ddd76f58c84d/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|53.91%|:green_apple:|

|Total Project Coverage|58.18%|:green_apple:|
|:-|:-:|:-:|

**Review by olexandra-shokotko — APPROVED** [review]
Everything looks good

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [60.99%]|:green_apple:|
|:-|:-:|:-:|
|[WeekService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/655d5eb5040d6d4d7d0a10399c6636a721f978b4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FWeekService.java)|100%|:green_apple:|
|[BookingForm.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/655d5eb5040d6d4d7d0a10399c6636a721f978b4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingForm.java)|56.73%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/655d5eb5040d6d4d7d0a10399c6636a721f978b4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|53.91%|:green_apple:|

|Total Project Coverage|58.18%|:green_apple:|
|:-|:-:|:-:|

**Pull request merged**
