### PR TITLE
:bug: Refactor BookingDto

### PR DESCRIPTION
**Pull request by CalculusEnjoyer**
Refactor outdated fields in BookingDto.

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [0%]|:x:|
|:-|:-:|:-:|
|[BookingDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/98c20e145c4e71f3ff65fb4dea24613ffe18c7cc/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|0%|:x:|

|Total Project Coverage|31.84%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [0%]|:x:|
|:-|:-:|:-:|
|[BookingDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/ebc3aad4dec0da6b93851c171da11bafa4878d59/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|0%|:x:|

|Total Project Coverage|31.84%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [0%]|:x:|
|:-|:-:|:-:|
|[BookingDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/a1efdcf4aca335f7991eaef8795f137c64da0a36/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingDto.java)|0%|:x:|

|Total Project Coverage|31.84%|:green_apple:|
|:-|:-:|:-:|

**Review by VladOSIO2 — APPROVED** [review]
Approved those changes as correct after discussion on the daily meeting

**Pull request merged**
