### PR TITLE
Implement DELETE "/bookings/{bookingId}" in CoordinatorController

### PR DESCRIPTION
**Pull request by CalculusEnjoyer**
Implement DELETE "/bookings/{bookingId}" in CoordinatorController and write test for it.
Add throwing BookingNotFoundException in BookingService deleteBookingById() and getBookingById()

### CODE REVIEW

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [23.97%]|:green_apple:|
|:-|:-:|:-:|
|[BookingNotFoundException.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/c530e94c8767cfbcc08d8d29356b85fceadc316f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fexceptions%2FBookingNotFoundException.java)|100%|:green_apple:|
|[BookingService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/c530e94c8767cfbcc08d8d29356b85fceadc316f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingService.java)|74.55%|:green_apple:|
|[InterviewApplicationException.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/c530e94c8767cfbcc08d8d29356b85fceadc316f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fexceptions%2FInterviewApplicationException.java)|57.14%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/c530e94c8767cfbcc08d8d29356b85fceadc316f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|45.45%|:green_apple:|
|[InterviewerController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/c530e94c8767cfbcc08d8d29356b85fceadc316f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|6.29%|:x:|
|[CandidateSlotDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/c530e94c8767cfbcc08d8d29356b85fceadc316f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotDto.java)|0%|:x:|
|[InterviewerSlotDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/c530e94c8767cfbcc08d8d29356b85fceadc316f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|0%|:x:|
|[InterviewerDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/c530e94c8767cfbcc08d8d29356b85fceadc316f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerDto.java)|0%|:x:|

|Total Project Coverage|30.64%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [23.97%]|:green_apple:|
|:-|:-:|:-:|
|[BookingNotFoundException.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/56e2f2061676e621ef5d06c827a82c3e7e6a6216/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fexceptions%2FBookingNotFoundException.java)|100%|:green_apple:|
|[BookingService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/56e2f2061676e621ef5d06c827a82c3e7e6a6216/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingService.java)|74.55%|:green_apple:|
|[InterviewApplicationException.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/56e2f2061676e621ef5d06c827a82c3e7e6a6216/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fexceptions%2FInterviewApplicationException.java)|57.14%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/56e2f2061676e621ef5d06c827a82c3e7e6a6216/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|45.45%|:green_apple:|
|[InterviewerController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/56e2f2061676e621ef5d06c827a82c3e7e6a6216/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|6.29%|:x:|
|[CandidateSlotDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/56e2f2061676e621ef5d06c827a82c3e7e6a6216/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotDto.java)|0%|:x:|
|[InterviewerSlotDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/56e2f2061676e621ef5d06c827a82c3e7e6a6216/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|0%|:x:|
|[InterviewerDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/56e2f2061676e621ef5d06c827a82c3e7e6a6216/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerDto.java)|0%|:x:|

|Total Project Coverage|30.64%|:green_apple:|
|:-|:-:|:-:|

**Comment by CalculusEnjoyer** [comment]
|File|Coverage [23.97%]|:green_apple:|
|:-|:-:|:-:|
|[BookingNotFoundException.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/913180b9ededcf64dd94a0500c20de633c8c994c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fexceptions%2FBookingNotFoundException.java)|100%|:green_apple:|
|[BookingService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/913180b9ededcf64dd94a0500c20de633c8c994c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingService.java)|75.44%|:green_apple:|
|[InterviewApplicationException.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/913180b9ededcf64dd94a0500c20de633c8c994c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fexceptions%2FInterviewApplicationException.java)|57.14%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/913180b9ededcf64dd94a0500c20de633c8c994c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|43.4%|:green_apple:|
|[InterviewerController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/913180b9ededcf64dd94a0500c20de633c8c994c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|6.29%|:x:|
|[CandidateSlotDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/913180b9ededcf64dd94a0500c20de633c8c994c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotDto.java)|0%|:x:|
|[InterviewerSlotDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/913180b9ededcf64dd94a0500c20de633c8c994c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|0%|:x:|
|[InterviewerDto.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/913180b9ededcf64dd94a0500c20de633c8c994c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerDto.java)|0%|:x:|

|Total Project Coverage|30.64%|:green_apple:|
|:-|:-:|:-:|

**Review by Archasmiel — APPROVED** [review]
OK

**Pull request merged**
